version: '3.4'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    ports:
      - "${ADMINER_HOST_PORT}:${ADMINER_CONTAINER_PORT}"

volumes:
  postgres:
    driver: local
